@startuml
'https://plantuml.com/class-diagram

class student_seq

class exam_result_seq

class student {
    id: bigint
    full_name: varchar(255)
}

class exam_result {
    id: bigint
    name: varchar(255)
    result: int
    student_id: bigint
}

student "one" ||--o{ "many" exam_result

@enduml